spring.application.name=pametna-kupovina-backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.default-schema=app
spring.flyway.schemas=app
spring.flyway.validate-migration-naming=true

spring.sql.init.mode=never

management.endpoint.health.show-details=always